name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Package Flask app
      - name: Package Flask app
        run: |
          chmod +x build_scripts/pack.sh
          ./build_scripts/pack.sh

      # Upload build.zip to S3
      - name: Upload build.zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_ARTIFACT_BUCKET: ${{ secrets.APP_ARTIFACT_BUCKET }}
        run: |
          aws s3 cp build.zip s3://$APP_ARTIFACT_BUCKET/build.zip

      # Terraform Init & Apply
      - name: Terraform Init & Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
          TF_STATE_LOCK_TABLE: ${{ secrets.TF_STATE_LOCK_TABLE }}
        run: |
          cd infra/terraform
          terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" -backend-config="region=ap-south-1"
          terraform apply -auto-approve

      # Deploy via Ansible
      - name: Deploy via Ansible
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_ARTIFACT_BUCKET: ${{ secrets.APP_ARTIFACT_BUCKET }}
          KEY_NAME: ${{ secrets.KEY_NAME }}
        run: |
          cd infra/ansible
          ansible-playbook -i inventory playbook.yml
